language: python
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -r tests/requirements.txt
  - (cd frontend && yarn install)
  - (cd frontend && yarn start &)
script:
  - make test
notifications:
  email:
  - stollenwerk@kitconcept.com
